name: CombatV3
version: '${version}'
main: org.main.uneton.Combat
api-version: '1.19'
author: unetonn

softdepend:
  - Vault

commands:
  cage:
    description: Create a cube around the player that the player cannot break.
    usage: /cage <player>
  crash:
    description: Spawns a white ball around you.
    usage: /crash <player>
  flyspeed:
    description: Makes player flyspeed faster.
    usage: /flyspeed <number>
  freeze:
    description: Cancels the player's movement.
    usage: /freeze <player>
  gm:
    description: makes the player invulnerable to all faults.
    usage: /gm <player>
  cure:
    description: Heals the player's hearts.
    usage: /cure <player>
  invsee:
    description: See the inventory of other players.
    usage: /invsee <player>
  launch:
    description: Throws the player high into the air
    usage: /launch <player>
  givestick:
    description: Gives the player a magic toy Stick
    usage: /givestick <player>
  slippery:
    description: Drops Items from the player.
    usage: /slippery <player>
  vanish:
    description: Toggles vanish mode.
    usage: /vanish

  setspawn:
    description: Sets the server spawn point!
    usage: /setspawn
  spawn:
    description: Teleport to the spawnpoint.
    usage: /spawn

  bugreport:
    description: Report a bug. reporting false bugs will be punished!
    usage: /bugreport
  daily:
    description: Command that canbe used daily for a reward!
    usage: /daily
  enderchest:
    description: Opens your personal Enderchest.
    usage: /enderchest
  guide:
    description: plugin commands.
    usage: /guide <text>
  ping:
    description: Check player ping.
    usage: /ping <player>
  playtime:
    description: Total playtime of a specified player in the game.
    usage: /playtime <player>
  puu:
    description: Spawns an oak tree at the player's location.
    usage: /puu
  repair:
    description: Repairs the durability of your armor.
    usage: /repair
  rules:
    description: Original Rules Of The Server.
    usage: /rules
  sign:
    description: Spawns you a sign. (Can be clicked!)
    usage: /sign
  sudo:
    description: Executes another player perform a task.
    usage: /sudo <target> <command>
  trash:
    description: Put your stuff in the menu and close it!
    usage: /trash
  tp:
    description: Teleports to or from the player.
    usage: /tp <player> <target>
  msg:
    description: Send a whisper to the player.
    usage: /msg <player> <message>