name: CombatV3
version: '${version}'
main: org.main.uneton.Combat
api-version: '1.19'
softdepend:
  - Vault

commands:
  clearchat:
    permission: combat.clearchat.use
    permission-message: Permission Denied, You do not have permission to do this task.
    description: Clears the chat.
    usage: /clearchat
  crash:
    permission: combat.crash.use
    permission-message: Permission Denied, You do not have permission to do this task.
    description: Spawns a white ball around you.
    usage: /crash <player>
  heal:
    permission: combat.heal.use
    permission-message: Permission Denied, You do not have permission to do this task.
    description: Heals the player's hearts.
    usage: /heal <player>
  invsee:
    permission: combat.invsee.use
    permission-message: Permission Denied, You do not have permission to do this task.
    description: See the inventory of other players.
    usage: /invsee <player>
  repair:
    permission: combat.repair.use
    permission-message: Permission Denied, You do not have permission to do this task.
    description: Repairs the durability of one or all items.
    usage: /repair <all>
  setspawn:
    permission: combat.setspawn.use
    permission-message: Permission Denied, You do not have permission to do this task.
    description: Sets the server spawn point!
    usage: /setspawn
  slippery:
    permission: combat.slippery.use
    permission-message: Permission Denied, You do not have permission to do this task.
    description: Drops Items from the player.
    usage: /slippery <player>
  trap:
    permission: combat.trap.use
    permission-message: Permission Denied, You do not have permission to do this task.
    description: Create a cube around the player that the player cannot break.
    usage: /trap <player>

  spawn:
    description: Teleports you to the spawn.
    usage: /spawn

  enderchest:
    description: Opens your personal Ender chest.
    usage: /enderchest
  guide:
    description: plugin commands.
    usage: /guide <info>
  playtime:
    description: Time that you have played in total on the server.
    usage: /playtime <player>
  rules:
    description: Rules of the Server.
    usage: /rules
  sign:
    permission: combat.sign.use
    permission-message: Permission Denied, You do not have permission to do this task.
    description: Spawns you a sign. (Can be clicked!)
    usage: /sign
  sudo:
    description: Executes another player perform a task.
    usage: /sudo <player> <text>

  gm:
    permission: combat.gm.use
    permission-message: Permission Denied, You do not have permission to do this task.
    description: makes the player invulnerable to all faults.
    usage: /gm <player>
  ignorelist:
    description: Checks all ignored players.
    usage: /ignorelist
  ignore:
    description: Ignore a player.
    usage: /ignore <player>
  unignore:
    description: un-ignores a player.
    usage: /unignore <player>
  suicide:
    description: Causes you to perish.
    usage: /suicide
  disposal:
    description: you can put here items that you want to deleted permanently!
    usage: /disposal