name: CombatV3
version: '${version}'
main: org.main.uneton.Combat
api-version: '1.19'
author: unetonn

commands:
  cage:
    description: Create a cube around the player that the player cannot break.
    usage: /cage <player>
  clear:
    description: Clears items from player inventory, including items.
    usage: /clear <player>
  crash:
    description: Spawns a white ball around you.
    usage: /crash <player>
  freeze:
    description: Cancels the player's movement.
    usage: /freeze <player>
  gm:
    description: makes the player invulnerable to all faults.
    usage: /gm <player>
  cure:
    description: Heals the player's hearts.
    usage: /cure <player>
  invsee:
    description: See the inventory of other players.
    usage: /invsee <player>
  launch:
    description: Throws the player high into the air
    usage: /launch <player>
  magictrick:
    description: a cool magictrick thats worth it :)
    usage: /magictrick <player>
  slippery:
    description: Drops Items from the player.
    usage: /slippery <player>
  vanish:
    description: Toggles vanish mode.
    usage: /vanish

  block:
    description: Block a player.
    usage: /block <help>
  blocklist:
    description: List blocked players.
    usage: /blocklist
  unblock:
    description: Unblock a player.
    usage: /unblock <player>

  setspawn:
    description: Sets the server spawn point!
    usage: /setspawn
  spawn:
    description: Teleport to the spawnpoint.
    usage: /spawn

  daily:
    description: Command that canbe used daily for a reward!
    usage: /daily
  enderchest:
    description: Opens your personal Enderchest.
    usage: /enderchest
  guide:
    description: plugin commands.
    usage: /guide <text>
  ping:
    description: Check player ping.
    usage: /ping <player>
  puu:
    description: Spawns an oak tree at the player's location.
    usage: /puu
  repair:
    description: Repairs the durability of your armor.
    usage: /repair
  sign:
    description: Spawns you a sign. (Can be clicked!)
    usage: /sign
  sudo:
    description: Executes another player perform a task.
    usage: /sudo <target> <command>
  trash:
    description: Put your stuff in the menu and close it!
    usage: /trash
  tp:
    description: Teleports to or from the player.
    usage: /tp <player> <target>
  msg:
    description: Send a whisper to the player.
    usage: /msg <player> <message>
  time:
    description: Sets the time to day or night.
    usage: /time <day|night>